name: Build Windows EXE + Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: Get-ChildItem -Recurse

      - name: Check main.py exists
        run: |
          if (!(Test-Path "main.py")) {
            Write-Error "main.py not found in repository root."
          }

      - name: Check requirements.txt exists
        run: |
          if (!(Test-Path "requirements.txt")) {
            Write-Error "requirements.txt not found in repository root."
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --noconfirm --onefile --name RhinoSimPro main.py

      - name: List build outputs
        run: Get-ChildItem -Recurse dist

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Check Inno Setup script exists
        run: |
          if (!(Test-Path "installer\RhinoSimPro.iss")) {
            Write-Error "installer\RhinoSimPro.iss not found."
          }

      - name: Build Installer (Inno Setup)
        run: >
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\RhinoSimPro.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RhinoSimPro-Installer
          path: |
            dist\RhinoSimPro.exe
            installer\Output\Setup.exe      path: |
            dist\RhinoSimPro.exe
            installer\Output\Setup.exe
