name: Build Windows EXE + Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: dir /s

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --noconfirm --onefile --name RhinoSimPro main.py

      - name: List build outputs
        run: dir dist

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Build Installer (Inno Setup)
        run: >
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\RhinoSimPro.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RhinoSimPro-Installer
          path: |
            dist\RhinoSimPro.exe
            installer\Output\Setup.exe
