name: Build Windows EXE + Installer with Debug Logs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: STEP 1: Setting up virtual environment
      run: |
        python -m venv .venv
        .venv\Scripts\python -m pip install --upgrade pip
        .venv\Scripts\python -m pip install -r requirements.txt pyinstaller

    - name: STEP 2: Build EXE with PyInstaller
      run: |
        .venv\Scripts\pyinstaller --noconfirm --onefile --name RhinoSimPro main.py

    - name: STEP 3: List EXE
      run: |
        dir dist

    - name: STEP 4: Build Installer (Inno Setup)
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\RhinoSimPro.iss
